### ISSUE TITLE
Ability to Sign Up and Login

### ISSUE THREAD

**Issue by ronakkothari123** [ronakkothari123/Cricket-Scorecard#9]
Ability to have users organize themselves. Each use should have the following
- PFP Data (users upload image, and I'll shrink image and take image data and store as String)
- Email
- Password
- Teams (Array of Object "Teams"). Teams should store list of Strings (player names) and maybe match IDs (to calculate stats)
- Matches viewed/created
- Stats

Above list is subject to change

**Comment by ronakkothari123** [comment]
Let me know if you think of more stuff or if you believe the above list should be altered in any way.

**Comment by Advayp** [comment]
Sounds good.

**Comment by Advayp** [comment]
Running Checklist (for me):
 - [x] Profile Picture Data
 - [x] Email
 - [x] Password
 - [x] Teams
 - [x] Matches Created
 - [x] Stats

**Comment by ronakjkothari** [comment]
This is pretty lit, brother!
